config/routes.rb
Rails.application.routes.draw do

root 'sessions#new'

resources :doctors

  get 'doctors' => 'doctors#index'
  get 'doctors' => 'doctors#new'
  get '/doctors/:id/edit' => 'doctors#edit'
  put  '/doctors/:id/' => 'doctors#update'
  put   '/doctors/:id/edit'   => 'doctors#update' 

resources :patients

  get 'patients' => 'patients#index'
  get 'patients' => 'patients#new'
  get 'patients/:id' => 'patients#show'
  get '/patients/:id/edit' => 'patients#edit'
  put '/patients/:id/' => 'patients#update'
  put '/patients/:id/edit'   => 'patients#update' 

resources :appointments

  get 'appointments' => 'appointments#index'
  get 'appointments' => 'appointments#new'
  delete 'appointments' => 'appointments#destroy'

  resources :sessions

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	
	belongs_to :doctor
	belongs_to :patient

  def self.listing(page)
    order(created_at: :desc).page(params[:page]).per(20)
  end

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	
# attr_accessible :fname, :lname, :specialty, :password
	
 	has_many :appointments   
 	has_many :patients, through: :appointments

end

app/models/patient.rb
class Patient < ActiveRecord::Base

	 has_many :appointments
	 has_many :doctors, through: :appointments

	 	 	has_secure_password

def self.authenticate(email, password)
end

	 validates :email, presence: true, uniqueness: true
	 validates :fname, presence: { message: ", what's your name?"}
	 validates :illness, presence: { message: ", what's wrong?"}
	 validates :password, confirmation: true, presence: true, length: {minimum: 4, maximum: 30}
 

	after_save :new_patient_haiku

 	def new_patient_haiku 
 	 Rails.logger.info( 
 	 	"""""
 	 	uh oh 911
		new patient alive or dead
		hospital break room
		!!!
		"""""
	  	)
 	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


   helper_method :current_patient
 
   def current_patient
     @current_patient ||= Patient.find(session[:patient_id]) if session[:patient_id]
   end 

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	def index
    @appointments = Appointment.all
	end

  def create
    @appointment = Appointment.new(user_params)
    @appointment.patient_id = current_patient.id if current_patient
      if @appointment.save
        session[:appointment_id] = @appointment.id
        redirect_to appointments_path
      else
        redirect_to appointments_path
      end
  end

  def destroy
    @appointment = Appointment.find params[:id]
    @appointment.destroy
    redirect_to appointments_path
  end
  
  private 

  def user_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :room, :time) 
  end 

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	def index
    	@doctors = Doctor.all
	end

  def create
    @doctor = Doctor.new(doctor_params)
      if @doctor.save
        session[:doctor_id] = @doctor.id
        redirect_to doctors_path
      else
        redirect_to doctors_path
      end
  end

  def new
    @doctor = Doctor.new
  end


  def edit
    @doctor = Doctor.find params[:id]
  end

  def update
    @doctor = Doctor.find params[:id]
    @doctor.update_attributes(params.require(:doctor).permit(:fname, :lname, :specialty))
    redirect_to doctors_path


  end


  def destroy
    @doctor = Doctor.find params[:id]
    @doctor.destroy
    redirect_to doctors_path
  end



  private 

  def doctor_params
    params.require(:doctor).permit(:fname, :lname, :specialty, :password)
  end 

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find params[:id]
  end

  def create
    @patient = Patient.new(user_params)
      if @patient.save
        session[:patient_id] = @patient.id
        redirect_to patients_path
      else
        render :new
      end
  end

  def new
    @patient = Patient.new
  end

  # edit action
  def edit
    @patient = Patient.find params[:id]
  end

  # update action
  def update
    @patient = Patient.find params[:id]
    @patient.update_attributes(params.require(:patient).permit(:email, :fname, :lname, :illness, :password))
    flash[:notice] = "Updated!"
    redirect_to edit_patient_path
  end

  # destroy action
  def destroy
    @patient = Patient.find params[:id]
    @patient.destroy
    redirect_to patients_path
  end


  private 

  def user_params
    params.require(:patient).permit(:email, :fname, :lname, :illness, :password)
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @patients = Patient.all
  end

  def create
    puts params[:email]
    patient = Patient.find_by_email(params[:session][:email])
    if patient && patient.authenticate(params[:session][:password])
      flash[:notice] = "You've been logged in."
      session[:patient_id] = patient.id
      redirect_to patients_path
    else
      render 'new'
      flash[:alert] = "There was a problem logging you in."
    end 
  end 

  def destroy
    session[:patient_id] = nil
    redirect_to root_url, notice: "Logged out."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


 
   def current_patient
     @current_patient ||= Patient.find(session[:patient_id]) if session[:patient_id]
   end 


end

app/helpers/appointments_helper.rb
module AppointmentsHelper

	

end

app/helpers/doctors_helper.rb
module DoctorsHelper



end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/appointments/index.html.erb
<h1>Appointment Index</h1>
<h3><em>List of all the appointments</em></h3> <p>

<ul>
<% @appointments.order(created_at: :desc).each do |appointment| %>
  <li> 
    <strong>Doctor Id:</strong> <%= appointment.doctor_id %><br />
    <strong>Patient Id:</strong> <%= appointment.patient_id %><br />
    <strong>Time:</strong> <%= appointment.time %><br /> 
    <strong>Room:</strong> <%= appointment.room %></br /><p>
  </li>
  <hr />
<% end %>
</ul>

app/views/appointments/new.html.erb
<h1>Appointment New</h1>

    <%= form_for :appointment, url: '/appointments' do |f| %>
		<%= f.collection_select :doctor_id, Doctor.all, :id, :fname %>
      <%= f.text_field :room, :placeholder => 'room number' %> 
      <%= f.datetime_field :time, :value => Time.now.strftime('%Y-%m-%d') %>
      <%= f.submit "Schedule", :class => "form-btn" %>
    <% end %>

app/views/doctors/edit.html.erb
<h1>Doctor Edit</h1>

    <%= form_for :doctor, method: :put do |f| %>
      <%= f.text_field :fname, :placeholder => 'First Name' %>
      <%= f.text_field :lname, :placeholder => 'Last Name' %>
      <%= f.text_field :specialty, :placeholder => 'Specialty' %> 
      <%= f.password_field :password, :placeholder => 'Password' %> 
      <%= f.submit  %>
      <% end %>

app/views/doctors/index.html.erb
<h1>Doctor Index</h1>
<h3><em>List of all the Doctors</h3></em><p>

<ul>
<% @doctors.each do |doctor| %>
  <li>  
    <strong>Doctor Id:</strong> <%= doctor.id %><br />
    <strong>First Name:</strong> <%= doctor.fname %><br />
    <strong>Last Name:</strong> <%= doctor.lname %><br />
    <strong>Specialty:</strong> <%= doctor.specialty %></br />
  </li>
  <hr />
<% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Doctor New</h1>

<div class="login">
  <div class="container">
    <%= form_for :doctor, url: '/doctors' do |f| %>
      <%= f.text_field :fname, :placeholder => 'First Name' %>
      <%= f.text_field :lname, :placeholder => 'Last Name' %>
      <%= f.text_field :specialty, :placeholder => 'Specialty' %> 
      <%= f.password_field :password, :placeholder => 'Password' %> 
      <%= f.submit "Sign up", :class => "form-btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doctor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>

<nav> 

  <% if current_patient %>
	  <%= link_to "All Doctors", doctors_path %> |
    <%= link_to "All Patients", patients_path %> |
  	<%= link_to "All Appointments", appointments_path %>
    <%= link_to "New Appointment", new_appointment_path %>  |  
    <%= link_to current_patient.fname, current_patient  %>
    <%= link_to "Logout", logout_path, method: :delete %> 

    <% else %>
    
    <%= link_to "Login", login_path %>
    <%= link_to "New Patient", new_patient_path %>

    <% end %>

</nav>

<%= yield %>

</body>
</html>

app/views/patients/edit.html.erb
<h1>Patient Edit</h1>

	<%= form_for :patient, method: :put do |f| %>
		<%= f.text_field :email, :placeholder => 'Email' %> <br>
		<%= f.text_field :fname, :placeholder => 'First Name' %> <br>
		<%= f.text_field :lname, :placeholder => 'Last Name' %> <br>
		<%= f.text_field :illness, :placeholder => 'Illness' %> <br>
		<%= f.password_field :password, :placeholder => 'Password' %> <br>
		<%= f.submit %>
	<% end %>

app/views/patients/index.html.erb
<h1>Patient Index</h1>
<h3><em>list of all the patients</em></h3>


<ul>
<% @patients.each do |patient| %>
  <li>  
  	<strong>Patient Email:</strong> <%= patient.email %><br />
    <strong>Patient Id:</strong> <%= patient.id %><br />
    <strong>First Name:</strong> <%= patient.fname %><br />
    <strong>Last Name:</strong> <%= patient.lname %><br />
    <strong>Illness:</strong> <%= patient.illness %></br />


  </li>
  <hr />
<% end %>
</ul>

app/views/patients/new.html.erb
<h1>Patient New</h1>

<div class="login">
  <div class="container">
    <%= form_for :patient, url: '/patients' do |f| %>
      <%= f.text_field :email, :placeholder => 'Email' %>  </Br>
      <%= f.text_field :fname, :placeholder => 'First Name' %>  </Br>
      <%= f.text_field :lname, :placeholder => 'Last Name' %>  </Br>
      <%= f.text_field :illness, :placeholder => 'Illness' %>  </Br>
      <%= f.password_field :password, :placeholder => 'Password' %>   </Br>
      <%= f.submit "Sign up", :class => "form-btn" %>
    <% end %>
  </div>
</div>


<% if @patient.errors.full_messages.any? %>
   <ul>
        <% @patient.errors.full_messages.each do |error_message| %>
       <li><%= error_message%></li>
       <br/>
<% end %>   
</ul> 
<% end %>

app/views/patients/show.html.erb
<h1>Patient Show</h1>

<strong>Id:</strong> <%= @patient.id %><br />
<strong>Email:</strong> <%= @patient.email %><br />
<strong>First Name:</strong> <%= @patient.fname %><br />
<strong>Last Name:</strong> <%= @patient.lname %><br />
<strong>Password:</strong> <%= @patient.password %><br />
<p>
<%= link_to "Edit Patient", edit_patient_path(@patient) %>
<%= link_to "Delete Patient", patient_path(@patient), method: :delete %>
</p>